---
  name: Guard Main Branch

  on:
    pull_request:
      types:
        - auto_merge_enabled
      branches:
        - main
    merge_group:

  permissions:
    contents: read

  jobs:
    guardian-jobs:
      uses: ec-intl/.github/.github/workflows/guard_template.yml@cm/add-public-workflow
      secrets: inherit
